[package]
name = "watermill"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-recursion = "1.0.0"
chrono = "0.4.22"
clap = { version = "4.0.17", features = ["derive"] }
csv = "1.1.6"
directories = "4.0.1"
tokio = { version = "1.21", features = ["full"] }
pnet = { version = "0.31.0", features = ["std"] }
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1", features = ["derive"] }

[profile.release]
lto = true