[package]
name = "watermill"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-recursion = "1.0.4"
chrono = "0.4.24"
clap = { version = "4.2.2", features = ["derive"] }
csv = "1.2.1"
directories = "5.0.0"
tokio = { version = "1.27.0", features = ["full"] }
pnet = { version = "0.33.0", features = ["std"] }
reqwest = { version = "0.11.16", features = ["json"] }
serde = { version = "1.0.160", features = ["derive"] }
sudo = "0.6.0"

[profile.release]
lto = true